services:
  prerender:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: prerender-server
    ports:
      - "3000:3000"
    environment:
      - PRERENDER_PORT=3000
      - NODE_ENV=production
      - CHROME_BIN=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - default
      - nginx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN

networks:
  nginx-network:
    external: true
